In [1]:
date= pd.read_csv(r"\Users\Anjli Kumari\datasets\orders.csv")
time= pd.read_csv(r"\Users\Anjli Kumari\datasets\messages.csv")

In [2]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [3]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [4]:
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   str
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), str(1)
memory usage: 31.4 KB

In [5]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [6]:
date['date'] = pd.to_datetime(date['date'])
date.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[us]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[us](1), int64(3)
memory usage: 31.4 KB

In [7]:
date['year'] = date['date'].dt.year
date.sample(5)

          date  product_id  city_id  orders  year
282 2019-10-27        1517       13       1  2019
112 2019-03-21        5787       13     134  2019
12  2019-03-15        5665        5       1  2019
604 2019-12-05        5708       26       1  2019
51  2019-08-12        6344       26       1  2019

In [8]:
date['month'] = date['date'].dt.month
date.sample(5)

          date  product_id  city_id  orders  year  month
451 2018-12-23        7078       22       6  2018     12
362 2019-10-10        3734        4      25  2019     10
799 2019-12-01        7382       30      36  2019     12
936 2019-08-02        2051       13       1  2019      8
308 2018-07-27         664       24      15  2018      7

In [9]:
date['month_name'] = date['date'].dt.month_name()
date.sample(5)

          date  product_id  city_id  orders  year  month month_name
327 2019-03-26        6115       22      63  2019      3      March
212 2019-10-11        3340        9       1  2019     10    October
815 2019-12-08        3659       20       4  2019     12   December
456 2018-12-04        1622        9       4  2018     12   December
51  2019-08-12        6344       26       1  2019      8     August

In [10]:
# which day of month
date['day'] = date['date'].dt.day
date.sample(5)

          date  product_id  city_id  orders  year  month month_name  day
304 2018-09-15         438       22      12  2018      9  September   15
92  2019-05-30        5788        7      34  2019      5        May   30
385 2018-07-24        4306       14      11  2018      7       July   24
327 2019-03-26        6115       22      63  2019      3      March   26
11  2019-08-02        3311       22       6  2019      8     August    2

In [11]:
#which day of week
date['date_dow'] = date['date'].dt.dayofweek
date.head()

,date,product_id,city_id,orders,year,month,month_name,day,date_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [12]:
date['date_dow_name'] = date['date'].dt.day_name()

date.drop(columns=['product_id','city_id','orders']).head()

        date  year  month month_name  day  date_dow date_dow_name
0 2019-12-10  2019     12   December   10         1       Tuesday
1 2018-08-15  2018      8     August   15         2     Wednesday
2 2018-10-23  2018     10    October   23         1       Tuesday
3 2019-08-17  2019      8     August   17         5      Saturday
4 2019-01-06  2019      1    January    6         6        Sunday

In [13]:
date['date_is_weekend'] = np.where(date['date_dow_name'].isin(['Sunday', 'Saturday']), 1,0)
date.drop(columns=['product_id','city_id','orders']).head()

,date,year,month,month_name,day,date_dow,date_dow_name,date_is_weekend
0,2019-12-10,2019,12,December,10,1,Tuesday,0
1,2018-08-15,2018,8,August,15,2,Wednesday,0
2,2018-10-23,2018,10,October,23,1,Tuesday,0
3,2019-08-17,2019,8,August,17,5,Saturday,1
4,2019-01-06,2019,1,January,6,6,Sunday,1

In [16]:
#extract week of the year
date['date_week'] = date['date'].dt.isocalendar().week
date.drop(columns=['product_id','city_id','orders']).head()

,date,year,month,month_name,day,date_dow,date_dow_name,date_is_weekend,date_week
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,2019,1,January,6,6,Sunday,1,1

In [17]:
date['quarter'] = date['date'].dt.quarter
date.drop(columns=['product_id','city_id','orders']).head()

,date,year,month,month_name,day,date_dow,date_dow_name,date_is_weekend,date_week,quarter
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1

In [18]:
date['semester'] = np.where(date['quarter'].isin([1,2]), 1, 2)
date.drop(columns=['product_id','city_id','orders']).head()

,date,year,month,month_name,day,date_dow,date_dow_name,date_is_weekend,date_week,quarter,semester
0,2019-12-10,2019,12,December,10,1,Tuesday,0,50,4,2
1,2018-08-15,2018,8,August,15,2,Wednesday,0,33,3,2
2,2018-10-23,2018,10,October,23,1,Tuesday,0,43,4,2
3,2019-08-17,2019,8,August,17,5,Saturday,1,33,3,2
4,2019-01-06,2019,1,January,6,6,Sunday,1,1,1,1

In [19]:
import datetime
today = datetime.datetime.today()
today

datetime.datetime(2026, 8, 13, 15, 45, 23, 891016)

In [20]:
today - date['date']

0     2438 days 15:45:23.891016
1     2920 days 15:45:23.891016
2     2851 days 15:45:23.891016
3     2553 days 15:45:23.891016
4     2776 days 15:45:23.891016
                 ...
995   2866 days 15:45:23.891016
996   2807 days 15:45:23.891016
997   2655 days 15:45:23.891016
998   2720 days 15:45:23.891016
999   2494 days 15:45:23.891016
Name: date, Length: 1000, dtype: timedelta64[us]

In [21]:
(today - date['date']).dt.days

0      2438
1      2920
2      2851
3      2553
4      2776
       ...
995    2866
996    2807
997    2655
998    2720
999    2494
Name: date, Length: 1000, dtype: int64

In [25]:
np.round((today -date['date']) / np.timedelta64(1, 'W') / 4,0)

0       87.0
1      104.0
2      102.0
3       91.0
4       99.0
       ...
995    102.0
996    100.0
997     95.0
998     97.0
999     89.0
Name: date, Length: 1000, dtype: float64

In [26]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   str
 1   msg     1000 non-null   str
dtypes: str(2)
memory usage: 15.8 KB

In [27]:
time['date'] = pd.to_datetime(time['date'])

In [28]:
time.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[us]
 1   msg     1000 non-null   str
dtypes: datetime64[us](1), str(1)
memory usage: 15.8 KB

In [29]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [30]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [31]:
today - time['date']

0     4624 days 14:55:23.891016
1     4488 days 16:05:23.891016
2     4974 days 15:24:23.891016
3     4276 days 15:14:23.891016
4     4673 days 16:34:23.891016
                 ...
995   5263 days 14:55:23.891016
996   4584 days 16:31:23.891016
997   5049 days 16:08:23.891016
998   5165 days 16:11:23.891016
999   4437 days 16:20:23.891016
Name: date, Length: 1000, dtype: timedelta64[us]

In [32]:
(today - time['date'])/np.timedelta64(1,'s')

0      3.995673e+08
1      3.878211e+08
2      4.298091e+08
3      3.695013e+08
4      4.038069e+08
           ...
995    4.547769e+08
996    3.961171e+08
997    4.362917e+08
998    4.463143e+08
999    3.834156e+08
Name: date, Length: 1000, dtype: float64

In [33]:
(today - time['date'])/np.timedelta64(1,'m')

0      6.659455e+06
1      6.463685e+06
2      7.163484e+06
3      6.158354e+06
4      6.730114e+06
           ...
995    7.579615e+06
996    6.601951e+06
997    7.271528e+06
998    7.438571e+06
999    6.390260e+06
Name: date, Length: 1000, dtype: float64

In [34]:
(today - time['date'])/np.timedelta64(1,'h')

0      110990.923303
1      107728.089970
2      119391.406636
3      102639.239970
4      112168.573303
           ...
995    126326.923303
996    110032.523303
997    121192.139970
998    123976.189970
999    106504.339970
Name: date, Length: 1000, dtype: float64

In [39]:
(today - time['date'])/np.timedelta64(1,'W')

0      13.763755
1      13.359138
2      14.805482
3      12.728080
4      13.909793
         ...
995    15.665541
996    13.644906
997    15.028787
998    15.374031
999    13.207383
Name: date, Length: 1000, dtype: float64